import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { splitRationale } from "@/lib/rationale";
import type { CompanyProfile, RubricScore, ObservabilityData, SourceEvidence } from "@/types/rubric";
import type { ScrapedPage } from "@/lib/api/scraper";

interface ExportData {
  companyProfile: CompanyProfile;
  rubricScore: RubricScore;
  observability: ObservabilityData;
  /** Full list of pages scraped/analyzed (superset of observability.pagesUsed). */
  pages?: ScrapedPage[];
}

// jspdf-autotable augments the jsPDF instance with lastAutoTable at runtime
type jsPDFWithAutoTable = jsPDF & { lastAutoTable: { finalY: number } };

const COLORS = {
  primary: [79, 70, 229] as [number, number, number], // Indigo
  success: [34, 197, 94] as [number, number, number], // Green
  warning: [234, 179, 8] as [number, number, number], // Yellow
  danger: [239, 68, 68] as [number, number, number], // Red
  muted: [107, 114, 128] as [number, number, number], // Gray
  dark: [17, 24, 39] as [number, number, number], // Dark gray
};

// Layout constants — keep everything inside these margins
const MARGIN_LEFT = 20;
const MARGIN_RIGHT = 20;
const MARGIN_TOP = 20;
const MARGIN_BOTTOM = 22; // room for footer

function getScoreColor(score: number): [number, number, number] {
  if (score === 2) return COLORS.success;
  if (score === 1) return COLORS.warning;
  return COLORS.danger;
}

function getBandColor(band: string): [number, number, number] {
  switch (band) {
    case "Exemplary":
      return COLORS.success;
    case "Trusted":
      return [34, 211, 238]; // Cyan
    case "Credible":
      return COLORS.warning;
    default: // Developing
      return COLORS.danger;
  }
}

// Collapse letter-spaced text (e.g. "F e a t u r e   F r e e" → "Feature Free").
// If any run of 5+ single-char tokens appears, treat the whole string as
// letter-spaced: split by 2+ spaces (real word breaks), and within each chunk,
// if the majority of tokens are single characters, join them into one word.
function collapseLetterSpacing(s: string): string {
  if (!/(?:\S ){5,}\S/.test(s)) return s;
  return s
    .split(/ {2,}/)
    .map((chunk) => {
      const tokens = chunk.split(" ").filter(Boolean);
      if (tokens.length < 3) return chunk;
      const singles = tokens.filter((t) => t.length === 1).length;
      if (singles / tokens.length >= 0.6) return tokens.join("");
      return chunk;
    })
    .join(" ");
}

// Normalize typographic quotes and control chars so the built-in helvetica
// font renders them without weird spacing / boxes.
function sanitizeText(s: string): string {
  if (!s) return "";
  const normalized = s
    .replace(/[\u2018\u2019\u02BC]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, "-")
    .replace(/\u2026/g, "...")
    .replace(/\u2265/g, ">=")
    .replace(/\u2264/g, "<=")
    .replace(/\u00A0/g, " ")
    .replace(/[\t\r\n]+/g, " ");
  return collapseLetterSpacing(normalized).replace(/ {2,}/g, " ").trim();
}

export function exportToPDF({ companyProfile, rubricScore, observability, pages }: ExportData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - MARGIN_LEFT - MARGIN_RIGHT;
  let yPos = MARGIN_TOP;

  const checkPageBreak = (height: number) => {
    if (yPos + height > pageHeight - MARGIN_BOTTOM) {
      doc.addPage();
      yPos = MARGIN_TOP;
    }
  };

  // Write wrapped text at (x) and advance yPos. Paginates automatically.
  const writeWrapped = (
    text: string,
    x: number,
    lineHeight: number,
    maxWidth: number,
  ) => {
    const lines = doc.splitTextToSize(sanitizeText(text), maxWidth);
    lines.forEach((line: string) => {
      checkPageBreak(lineHeight);
      doc.text(line, x, yPos);
      yPos += lineHeight;
    });
  };

  const sectionHeading = (label: string, color: [number, number, number] = COLORS.dark) => {
    checkPageBreak(14);
    doc.setFontSize(14);
    doc.setTextColor(...color);
    doc.setFont("helvetica", "bold");
    doc.text(label, MARGIN_LEFT, yPos);
    doc.setFont("helvetica", "normal");
    yPos += 8;
  };

  // ─── Title ────────────────────────────────────────────────────────────────
  doc.setFontSize(24);
  doc.setTextColor(...COLORS.primary);
  doc.text("AVS Rubric Report", pageWidth / 2, yPos, { align: "center" });
  yPos += 12;

  // Evidence-based assessment statement
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  const shortDisclaimer =
    "AI-generated report. Review cited evidence before acting. Full disclosure at end of report.";
  const fullDisclaimer =
    "AI-generated report. This is an evidence-based assessment of your product's external value-system legibility, generated by AI (Google Gemini & OpenAI models via Lovable AI Gateway) from publicly available information at the time of analysis. Scores and rationales may contain errors — review the cited evidence before acting. Disclosure provided per EU AI Act Article 50.";
  const disclaimerLines = doc.splitTextToSize(sanitizeText(shortDisclaimer), contentWidth);
  doc.text(disclaimerLines, pageWidth / 2, yPos, { align: "center" });
  yPos += disclaimerLines.length * 4 + 8;

  // Company name
  doc.setFontSize(16);
  doc.setTextColor(...COLORS.dark);
  doc.text(companyProfile.companyName, pageWidth / 2, yPos, { align: "center" });
  yPos += 8;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  doc.text(
    `Generated on ${new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    })}`,
    pageWidth / 2,
    yPos,
    { align: "center" },
  );
  yPos += 15;

  // ─── Score & Band ─────────────────────────────────────────────────────────
  doc.setFillColor(...getBandColor(rubricScore.band));
  doc.roundedRect(MARGIN_LEFT, yPos, contentWidth, 30, 3, 3, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  const scorePercentage = Math.round((rubricScore.totalScore / rubricScore.maxScore) * 100);
  doc.text(
    `${rubricScore.totalScore}/${rubricScore.maxScore} (${scorePercentage}%)`,
    pageWidth / 2,
    yPos + 12,
    { align: "center" },
  );
  doc.setFontSize(12);
  doc.text(rubricScore.band, pageWidth / 2, yPos + 22, { align: "center" });
  yPos += 40;

  // ─── Company Profile ──────────────────────────────────────────────────────
  sectionHeading("Company Profile");

  const profileData = [
    ["Description", companyProfile.oneLineDescription],
    ["Mission", companyProfile.missionOrPositioning],
    ["Primary Users", companyProfile.primaryUsers],
    ["Economic Buyer", companyProfile.economicBuyerGuess],
    ["ICP", companyProfile.icpGuess.join(", ")],
    ["Product Surface", companyProfile.productSurface.toUpperCase()],
    [
      "Pricing Model",
      ({
        access: "Seat-based",
        consumption: "Usage-based",
        outcome: "Outcome-based",
        hybrid: "Hybrid",
        gated: "Enterprise / Contact Sales",
        unclassified: "Unknown",
      } as Record<string, string>)[companyProfile.model_type_l1] ?? companyProfile.model_type_l1,
    ],
    ["Value Unit", companyProfile.valueUnitGuess],
  ].map(([k, v]) => [k, sanitizeText(String(v ?? ""))]);

  autoTable(doc, {
    startY: yPos,
    head: [],
    body: profileData,
    theme: "plain",
    styles: { fontSize: 9, cellPadding: 3, overflow: "linebreak" },
    columnStyles: {
      0: { fontStyle: "bold", cellWidth: 40 },
      1: { cellWidth: contentWidth - 40 },
    },
    margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
  });
  yPos = (doc as jsPDFWithAutoTable).lastAutoTable.finalY + 12;

  // ─── Observability ────────────────────────────────────────────────────────
  sectionHeading("Observability");
  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  checkPageBreak(6);
  doc.text(
    `Level: ${observability.level}  •  Confidence: ${observability.confidenceScore}%`,
    MARGIN_LEFT,
    yPos,
  );
  yPos += 6;

  const fullPages = pages && pages.length > 0
    ? pages.map((p) => p.url)
    : observability.pagesUsed;
  checkPageBreak(6);
  doc.text(
    `Pages analyzed: ${fullPages.length}  —  see Appendix A for the full list.`,
    MARGIN_LEFT,
    yPos,
  );
  yPos += 12;

  // ─── Key Strengths ────────────────────────────────────────────────────────
  if (rubricScore.strengths.length > 0) {
    sectionHeading("Key Strengths", COLORS.success);
    autoTable(doc, {
      startY: yPos,
      head: [["Dimension", "Why It's Strong", "What It Enables"]],
      body: rubricScore.strengths.map((s) => [
        sanitizeText(s.dimension),
        sanitizeText(s.whyItIsStrong),
        sanitizeText(s.whatItEnables),
      ]),
      theme: "striped",
      styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: COLORS.success, textColor: [255, 255, 255] },
      margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
      tableWidth: contentWidth,
    });
    yPos = (doc as jsPDFWithAutoTable).lastAutoTable.finalY + 12;
  }

  // ─── Areas for Improvement ────────────────────────────────────────────────
  if (rubricScore.weaknesses.length > 0) {
    sectionHeading("Areas for Improvement", COLORS.danger);
    autoTable(doc, {
      startY: yPos,
      head: [["Dimension", "What's Missing", "Why It Matters"]],
      body: rubricScore.weaknesses.map((w) => [
        sanitizeText(w.dimension),
        sanitizeText(w.whatIsMissingOrUnclear),
        sanitizeText(w.whyItMatters),
      ]),
      theme: "striped",
      styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
      headStyles: { fillColor: COLORS.danger, textColor: [255, 255, 255] },
      margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
      tableWidth: contentWidth,
    });
    yPos = (doc as jsPDFWithAutoTable).lastAutoTable.finalY + 12;
  }

  // ─── Recommended Focus ────────────────────────────────────────────────────
  if (rubricScore.recommendedFocus?.focusArea) {
    sectionHeading("Recommended Focus", COLORS.primary);
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.dark);
    doc.setFont("helvetica", "bold");
    checkPageBreak(6);
    doc.text(sanitizeText(rubricScore.recommendedFocus.focusArea), MARGIN_LEFT, yPos);
    doc.setFont("helvetica", "normal");
    yPos += 6;

    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    writeWrapped(rubricScore.recommendedFocus.why, MARGIN_LEFT, 4.5, contentWidth);
    yPos += 3;

    doc.setFontSize(10);
    doc.setTextColor(...COLORS.dark);
    checkPageBreak(6);
    doc.text("First Two Actions:", MARGIN_LEFT, yPos);
    yPos += 5;
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    rubricScore.recommendedFocus.firstTwoActions.forEach((action, i) => {
      writeWrapped(`${i + 1}. ${action}`, MARGIN_LEFT + 3, 4.5, contentWidth - 3);
    });
    yPos += 3;

    doc.setFontSize(10);
    doc.setTextColor(...COLORS.dark);
    checkPageBreak(6);
    doc.text("What to Measure:", MARGIN_LEFT, yPos);
    yPos += 5;
    doc.setFontSize(9);
    doc.setTextColor(...COLORS.muted);
    writeWrapped(rubricScore.recommendedFocus.whatToMeasure, MARGIN_LEFT, 4.5, contentWidth);
    yPos += 8;
  }

  // ─── Dimension Scores ─────────────────────────────────────────────────────
  sectionHeading("Dimension Scores");

  // How-to-read explainer
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.dark);
  doc.setFont("helvetica", "bold");
  checkPageBreak(5);
  doc.text("How to read this section", MARGIN_LEFT, yPos);
  doc.setFont("helvetica", "normal");
  yPos += 5;

  doc.setFontSize(8.5);
  doc.setTextColor(...COLORS.muted);
  writeWrapped(
    "Score (0-2): 2 = clear, buyer-usable evidence is publicly visible. 1 = partial or indirect evidence — a buyer would still need to ask. 0 = not visible externally. N/O = not observable from public sources.",
    MARGIN_LEFT,
    4.2,
    contentWidth,
  );
  yPos += 1;
  writeWrapped(
    "Confidence (%) reflects how sure the engine is about the score based on the evidence found. \u2265 70% = high (multiple independent signals agree). 40-69% = moderate (some signals, but gaps or ambiguity). < 40% = low (thin or conflicting evidence — treat the score as directional).",
    MARGIN_LEFT,
    4.2,
    contentWidth,
  );
  yPos += 2;
  writeWrapped(
    "Per-dimension evidence (URLs + quotes) is in Appendix B.",
    MARGIN_LEFT,
    4.2,
    contentWidth,
  );
  yPos += 6;

  // Clean internal audit blocks + floor notes from rationale
  const cleanRationale = (rationale: string): string =>
    sanitizeText(
      splitRationale(rationale)
        .prose.replace(/\s*\[Score floored to \d+ based on \d+ public evidence signals?\.\]\s*/gi, "")
        .replace(/\s*\[Score floored[^\]]*\]\s*/gi, ""),
    );

  autoTable(doc, {
    startY: yPos,
    head: [["Dimension", "Score", "Conf.", "Rationale"]],
    body: rubricScore.dimensionScores.map((dim) => [
      sanitizeText(dim.dimension),
      dim.notObservable ? "N/O" : `${dim.score}/2`,
      `${Math.round(dim.confidence * 100)}%`,
      cleanRationale(dim.rationale),
    ]),
    theme: "striped",
    styles: { fontSize: 8, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: COLORS.primary, textColor: [255, 255, 255] },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { cellWidth: 15, halign: "center" },
      2: { cellWidth: 15, halign: "center" },
      3: { cellWidth: contentWidth - 70 },
    },
    margin: { left: MARGIN_LEFT, right: MARGIN_RIGHT },
    didParseCell: (data) => {
      if (data.section === "body" && data.column.index === 1) {
        const s = rubricScore.dimensionScores[data.row.index];
        if (s && !s.notObservable) {
          data.cell.styles.textColor = getScoreColor(s.score);
          data.cell.styles.fontStyle = "bold";
        }
      }
    },
  });
  yPos = (doc as jsPDFWithAutoTable).lastAutoTable.finalY + 12;

  // ─── Appendix A — Pages Analyzed ──────────────────────────────────────────
  doc.addPage();
  yPos = MARGIN_TOP;
  sectionHeading("Appendix A — Pages Analyzed");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  writeWrapped(
    `Total pages analyzed: ${fullPages.length}. Every URL below was scraped and evaluated by the scoring engine; the per-dimension evidence in Appendix B cites the specific URLs used to justify each score.`,
    MARGIN_LEFT,
    4.5,
    contentWidth,
  );
  yPos += 3;

  doc.setFontSize(8);
  fullPages.forEach((url, i) => {
    checkPageBreak(6);
    const line = `${i + 1}. ${url}`;
    const lines = doc.splitTextToSize(sanitizeText(line), contentWidth);
    lines.forEach((ln: string, idx: number) => {
      checkPageBreak(4);
      doc.setTextColor(...COLORS.primary);
      if (idx === 0) {
        doc.textWithLink(ln, MARGIN_LEFT, yPos, { url });
      } else {
        doc.textWithLink(ln, MARGIN_LEFT + 4, yPos, { url });
      }
      yPos += 3.8;
    });
    yPos += 0.5;
  });
  yPos += 6;

  // ─── Appendix B — Dimension Scored Evidence ───────────────────────────────
  doc.addPage();
  yPos = MARGIN_TOP;
  const evidenceDims = rubricScore.dimensionScores.filter(
    (d) => (d.sourceEvidence && d.sourceEvidence.length > 0) || (d.observed && d.observed.length > 0),
  );

  // If any dimension has sourceEvidence, that list is a curated subset the
  // engine cited — not the full evidence body. Mark as "Examples only".
  const hasEvidence = evidenceDims.some((d) => d.sourceEvidence && d.sourceEvidence.length > 0);
  const heading = hasEvidence
    ? "Appendix B — Dimension Scored Evidence (Examples Only)"
    : "Appendix B — Dimension Scored Observations";
  sectionHeading(heading);

  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  writeWrapped(
    hasEvidence
      ? "The engine cited these specific quotes when scoring each dimension. They are a representative subset of the evidence considered, not the full body — see Appendix A for every page analyzed."
      : "Observations recorded per dimension during scoring.",
    MARGIN_LEFT,
    4.5,
    contentWidth,
  );
  yPos += 4;

  evidenceDims.forEach((dim) => {
    checkPageBreak(18);
    // Dimension header
    doc.setFontSize(11);
    doc.setTextColor(...getScoreColor(dim.score));
    doc.setFont("helvetica", "bold");
    doc.text(
      `${sanitizeText(dim.dimension)}  (${dim.notObservable ? "N/O" : dim.score + "/2"})`,
      MARGIN_LEFT,
      yPos,
    );
    doc.setFont("helvetica", "normal");
    yPos += 5;

    const evList: SourceEvidence[] = dim.sourceEvidence ?? [];
    if (evList.length > 0) {
      evList.forEach((ev) => {
        checkPageBreak(10);
        // URL
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.primary);
        const urlLines = doc.splitTextToSize(sanitizeText(ev.url), contentWidth - 4);
        urlLines.forEach((ln: string, idx: number) => {
          checkPageBreak(4);
          if (idx === 0) {
            doc.textWithLink(ln, MARGIN_LEFT + 2, yPos, { url: ev.url });
          } else {
            doc.textWithLink(ln, MARGIN_LEFT + 4, yPos, { url: ev.url });
          }
          yPos += 4;
        });

        // Snippet
        if (ev.snippet) {
          doc.setFontSize(8);
          doc.setTextColor(...COLORS.muted);
          doc.setFont("helvetica", "italic");
          const snippet = `"${sanitizeText(ev.snippet)}"`;
          const snippetLines = doc.splitTextToSize(snippet, contentWidth - 6);
          snippetLines.forEach((ln: string) => {
            checkPageBreak(4);
            doc.text(ln, MARGIN_LEFT + 4, yPos);
            yPos += 4;
          });
          doc.setFont("helvetica", "normal");
        }
        yPos += 2;
      });
    } else if (dim.observed && dim.observed.length > 0) {
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.muted);
      dim.observed.forEach((obs) => {
        const obsLines = doc.splitTextToSize(`\u2022 ${sanitizeText(obs)}`, contentWidth - 4);
        obsLines.forEach((ln: string) => {
          checkPageBreak(4);
          doc.text(ln, MARGIN_LEFT + 2, yPos);
          yPos += 4;
        });
      });
    }

    // Uncertainty
    if (dim.uncertaintyReasons && dim.uncertaintyReasons.length > 0) {
      yPos += 1;
      doc.setFontSize(8);
      doc.setTextColor(...COLORS.dark);
      const label =
        dim.confidence >= 0.7
          ? "Uncertainty factors:"
          : dim.confidence >= 0.4
            ? "Why confidence is not higher:"
            : "Why confidence is low:";
      checkPageBreak(5);
      doc.text(label, MARGIN_LEFT + 2, yPos);
      yPos += 4;

      doc.setTextColor(...COLORS.muted);
      dim.uncertaintyReasons.forEach((r) => {
        const lines = doc.splitTextToSize(`\u2022 ${sanitizeText(r)}`, contentWidth - 6);
        lines.forEach((ln: string) => {
          checkPageBreak(4);
          doc.text(ln, MARGIN_LEFT + 4, yPos);
          yPos += 4;
        });
      });
    }

    yPos += 5;
  });

  // ─── Full Disclosure ──────────────────────────────────────────────────────
  doc.addPage();
  yPos = MARGIN_TOP;
  sectionHeading("Disclosure");
  doc.setFontSize(9);
  doc.setTextColor(...COLORS.muted);
  writeWrapped(fullDisclaimer, MARGIN_LEFT, 4.8, contentWidth);

  // ─── Footer on every page ─────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(
      `Page ${i} of ${pageCount} • AVS Rubric Report`,
      pageWidth / 2,
      pageHeight - 14,
      { align: "center" },
    );
    doc.text(
      "Created by ValueTempo. For more information about the report, contact us at hello@valuetempo.com.",
      pageWidth / 2,
      pageHeight - 9,
      { align: "center" },
    );
  }

  const sanitizedName = companyProfile.companyName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`${sanitizedName}_avs_rubric_report.pdf`);
}
