import { motion } from "framer-motion";
import ValueTempoLogo from "@/assets/ValueTempo_Logo.png";
import { Footer } from "@/components/Footer";
import { ArrowLeft, Shield } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

const Privacy = () => {
  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-transparent to-accent/5 pointer-events-none" />

      {/* Header */}
      <header className="relative z-10 border-b border-border/50 bg-background/80 backdrop-blur-sm">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link to="/">
              <img alt="ValueTempo" className="h-8" src={ValueTempoLogo} />
            </Link>
            <Link to="/">
              <Button variant="outline" size="sm" className="gap-2">
                AVS Rubric
              </Button>
            </Link>
          </div>
          <nav className="hidden md:flex items-center gap-6">
            <Link to="/methodology" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Methodology</Link>
            <Link to="/faq" className="text-sm text-muted-foreground hover:text-foreground transition-colors">FAQ</Link>
          </nav>
        </div>
      </header>

      {/* Content */}
      <main className="relative z-10 container mx-auto px-4 py-12 max-w-3xl">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
          <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>

          <div className="flex items-center gap-3 mb-6">
            <Shield className="w-8 h-8 text-primary" />
            <h1 className="text-4xl font-bold">Privacy & Data Handling</h1>
          </div>

          <p className="text-lg text-muted-foreground mb-10">
            How the AVS Rubric collects, processes, and protects your data.
          </p>

          <div className="prose prose-lg dark:prose-invert max-w-none space-y-10">
            <section>
              <h2 className="text-2xl font-semibold mb-3">What Data We Collect</h2>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li><strong>Account information:</strong> Email address and optional display name, collected during sign-up.</li>
                <li><strong>Submitted URLs:</strong> The website URLs you enter for analysis.</li>
                <li><strong>Scan results:</strong> The assessment output generated by the rubric, including dimension scores, evidence citations, and confidence labels.</li>
                <li><strong>Usage metadata:</strong> Which URLs were scanned, when, and by whom—used for rate limiting and abuse prevention.</li>
                <li><strong>Feedback:</strong> Optional star ratings and free-text feedback you submit about a report.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">How We Process Scan Data</h2>
              <p className="text-muted-foreground mb-3">
                When you submit a URL, the AVS Rubric performs the following steps:
              </p>
              <ol className="list-decimal pl-6 space-y-2 text-muted-foreground">
                <li><strong>Public content scraping:</strong> We retrieve publicly accessible text from the submitted website (homepage, pricing page, documentation). No login-gated or private content is accessed.</li>
                <li><strong>AI-powered analysis:</strong> The scraped content is sent to a large language model for structured evaluation against the AVS Rubric dimensions. No personal data is included in the AI prompt—only website content.</li>
                <li><strong>Result caching:</strong> Analysis results are cached for 7 days to ensure consistent outputs and reduce redundant processing. After expiry, a new scan produces a fresh analysis.</li>
                <li><strong>Evidence gap logging:</strong> If the rubric detects missing public evidence for a dimension, it logs the gap anonymously to improve future accuracy.</li>
              </ol>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">Data Retention</h2>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li><strong>Scan results:</strong> Cached for 7 days, then automatically expired.</li>
                <li><strong>Account profiles:</strong> Retained as long as your account exists.</li>
                <li><strong>Usage logs:</strong> Retained for operational purposes (rate limiting, abuse detection).</li>
                <li><strong>Feedback:</strong> Retained indefinitely to improve the rubric methodology.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">Data Security</h2>
              <p className="text-muted-foreground">
                All data is transmitted over HTTPS. Database access is protected by row-level security policies that restrict reads and writes to authenticated users and their own data. No scan results or profile information are shared with third parties. AI model providers process only website content—never your personal information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">Email Communications</h2>
              <p className="text-muted-foreground">
                You may receive product-related emails based on your account. You can opt out of all non-essential email communications at any time using the <strong>Email Preferences</strong> link in the footer of the landing page. Your preference is stored and respected immediately. We comply with CAN-SPAM, CASL, and GDPR requirements for email consent.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">Your Rights</h2>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li><strong>Access:</strong> You can view all your scan results and profile data within the application.</li>
                <li><strong>Correction:</strong> You can update your display name and email preferences at any time.</li>
                <li><strong>Deletion:</strong> Contact us to request full account and data deletion. We will respond within 45 days.</li>
                <li><strong>Opt-out:</strong> You can opt out of email communications via the footer link on the landing page.</li>
                <li><strong>Non-discrimination:</strong> We will not discriminate against you for exercising any of your privacy rights.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">California Privacy Rights (CCPA / CPRA)</h2>
              <p className="text-muted-foreground mb-4">
                If you are a California resident, the California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA) provide you with additional rights regarding your personal information.
              </p>

              <h3 className="text-lg font-semibold mb-2">Categories of Personal Information Collected</h3>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground mb-4">
                <li><strong>Identifiers:</strong> Email address, display name, user ID.</li>
                <li><strong>Internet activity:</strong> URLs submitted for analysis, scan usage logs, interaction with the application.</li>
                <li><strong>Inferences:</strong> Rubric scores and dimension assessments derived from publicly available website content (not from your personal information).</li>
              </ul>

              <h3 className="text-lg font-semibold mb-2">We Do Not Sell or Share Your Personal Information</h3>
              <p className="text-muted-foreground mb-4">
                We do <strong>not</strong> sell your personal information. We do <strong>not</strong> share your personal information for cross-context behavioral advertising. We have not sold or shared personal information in the preceding 12 months.
              </p>

              <h3 className="text-lg font-semibold mb-2">Your CCPA Rights</h3>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground mb-4">
                <li><strong>Right to Know:</strong> You may request the categories and specific pieces of personal information we have collected about you, the sources, the business purpose, and any third parties with whom it was shared.</li>
                <li><strong>Right to Delete:</strong> You may request deletion of your personal information. We will comply within 45 days and direct any service providers to do the same.</li>
                <li><strong>Right to Correct:</strong> You may request correction of inaccurate personal information.</li>
                <li><strong>Right to Opt-Out of Sale/Sharing:</strong> We do not sell or share your data, so no opt-out mechanism is required. If this changes, we will provide a "Do Not Sell or Share My Personal Information" link.</li>
                <li><strong>Right to Limit Use of Sensitive Information:</strong> We do not collect sensitive personal information as defined by the CCPA.</li>
                <li><strong>Non-Discrimination:</strong> We will not deny services, charge different prices, or provide a different quality of service because you exercised your CCPA rights.</li>
              </ul>

              <h3 className="text-lg font-semibold mb-2">How to Submit a Request</h3>
              <p className="text-muted-foreground mb-4">
                To exercise any of these rights, email us at{" "}
                <a href="mailto:privacy@valuetempo.com" className="text-primary hover:underline">privacy@valuetempo.com</a>.
                We may verify your identity before fulfilling a request. You may also designate an authorized agent to make a request on your behalf.
              </p>

              <h3 className="text-lg font-semibold mb-2">Disclosure of Personal Information</h3>
              <p className="text-muted-foreground">
                In the preceding 12 months, we have disclosed the following categories of personal information for a business purpose: Internet activity data (website content only, not personal data) shared with AI model providers for rubric analysis. No personal identifiers are shared with third parties.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-3">Third-Party Services</h2>
              <p className="text-muted-foreground">
                The AVS Rubric uses the following third-party services to deliver its functionality:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-muted-foreground">
                <li><strong>AI model providers:</strong> For rubric analysis. Only public website content is shared—never personal data.</li>
                <li><strong>Cloudflare Turnstile:</strong> For bot protection during scan submission. Subject to Cloudflare's privacy policy.</li>
              </ul>
            </section>

            <section className="border-t border-border/50 pt-8">
              <p className="text-sm text-muted-foreground">
                Last updated: February 2026. For questions about data handling, contact us at{" "}
                <a href="mailto:privacy@valuetempo.com" className="text-primary hover:underline">privacy@valuetempo.com</a>.
              </p>
            </section>
          </div>
        </motion.div>
      </main>
      <Footer />
    </div>
  );
};

export default Privacy;
