// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-my-scans.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_scans_default = defineTool({
  name: "list_my_scans",
  title: "List my scans",
  description: "List the AVS Rubric scans the signed-in user has run, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max number of scans to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("scan_usage").select("id, scanned_url, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scans: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-scan-result.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.110.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_scan_result_default = defineTool2({
  name: "get_scan_result",
  title: "Get scan result",
  description: "Fetch the full AVS Rubric scan result (company profile, dimension scores, strengths, weaknesses) for a given URL domain. Returns the most recent non-expired scan for that domain.",
  inputSchema: {
    url_domain: z2.string().trim().min(1).describe("The URL domain of the scan to retrieve (e.g. 'example.com').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ url_domain }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("scan_results").select("id, url_domain, created_at, expires_at, result_json").eq("url_domain", url_domain).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No scan found for domain ${url_domain}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { scan: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jntwewypahlzknvcczgl";
var mcp_default = defineMcp({
  name: "valuetempo-avs-rubric-mcp",
  title: "ValueTempo AVS Rubric",
  version: "0.1.0",
  instructions: "Tools for the ValueTempo AVS Rubric app. Use `list_my_scans` to see the signed-in user's recent scans, and `get_scan_result` to retrieve the full rubric result (company profile, dimension scores, strengths, weaknesses) for a given URL domain.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_my_scans_default, get_scan_result_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
